In [3]:
import numpy as np
a=[f'q{i}' for i in range(17)]
print(a)

['q0', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q12', 'q13', 'q14', 'q15', 'q16']


In [6]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
import cirq
cirq.unitary(cirq.I)
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [8]:
from scipy.linalg import sqrtm
s02 = np.array([[0],[0],[1],[0],[0],[0],[0],[0],[0]])
# s02
s11 = np.array([[0],[0],[0],[0],[1],[0],[0],[0],[0]])
# s11
K1 = (np.dot(s02,s11.T)+np.dot(s11,s02.T))
sqrtm(np.identity(9)-K1.T.conjugate()*K1)
# K1

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.70710678,  0.        , -0.70710678,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.70710678,  0.        ,  0.70710678,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0

In [24]:
cirq.bit_flip

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [6]:
cirq.reset
channel = np.zeros((3,) * 3, dtype=np.complex64)
channel[:, 0, :] = np.eye(3)
channel

array([[[1.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 1.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]]], dtype=complex64)

In [ ]:
cirq.AmplitudeDampingChannel

In [9]:
cirq.partial_trace(np.array([[1,2,3],[4,5,6],[7,8,9]]),keep_indices=[0])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
from numpy import random
random.random()

0.3144994068603816

In [15]:
[1,2,3,]

[1, 2, 3]

In [17]:
import time


def cost(func):
    def warpper(*args, **kwargs):
        t1 = time.time()
        res = func(*args, **kwargs)
        t2 = time.time()
        print(func.__name__ + "执行耗时" +  str(t2-t1))
        return res
    return warpper


@cost
def test(sleep_time):
    time.sleep(sleep_time)

test(1)

test执行耗时1.0129320621490479


In [18]:
class TestCall():
    def __call__(self, *args, **kwargs):
        print("执行了call方法")

tc = TestCall()
tc()
print(callable(tc))

执行了call方法
True


In [19]:
import time


class Decorator(object):
    def __init__(self, func):
        self.func = func

    def __call__(self, *args, **kwargs):
        t1 = time.time()
        res = self.func(*args, **kwargs)
        t2 = time.time()
        print("函数执行时长:"+ str(t2 - t1))


@Decorator
def test():
    time.sleep(1.5)

test()

函数执行时长:1.5104544162750244


In [20]:
from inspect import isfunction

class MyMeta(type):
    def __new__(cls, *args, **kwargs):
        _class = super().__new__(cls, *args, **kwargs)
        if _class.__name__ != 'Animal':
            if not hasattr(_class, 'run') or not isfunction(getattr(_class, 'run')):
                raise Exception('类{name}没有实现run方法'.format(name=_class.__name__))
        return _class


class Animal(metaclass=MyMeta):
    def __init__(self, name):
        self.name = name


class Cat(Animal):
    def __init__(self, name):
        super().__init__(name)

cat = Cat('加菲猫')

Exception: 类Cat没有实现run方法

In [21]:
class Cat(Animal):
    def __init__(self, name):
        super().__init__(name)

    def run(self):
        print('run')

cat = Cat('加菲猫')
cat.run()

run


In [27]:
class Money:
    def __init__(self, value):
        self.value = value

    def __gt__(self, other):
        return self.value*self.rate > other.value*other.rate


class Dollar(Money):
    def __init__(self, value):
        super().__init__(value)
        self.rate = 0.1       # 与美元的汇率


class Rmb(Money):
    def __init__(self, value):
        super().__init__(value)
        self.rate = 1      # 1元人民币等于0.1431美元


d = Dollar(95)
r = Rmb(6.7)

print(d > r)

True


In [4]:
import requests

payload = {'name': '小明', 'age': '14'}
res = requests.post("http://httpbin.org/post", data=payload)
print(res.text)

{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {
    "age": "14", 
    "name": "\u5c0f\u660e"
  }, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Content-Length": "30", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.27.1", 
    "X-Amzn-Trace-Id": "Root=1-634b7127-5405f3041b7be60f4133b8ec"
  }, 
  "json": null, 
  "origin": "43.206.52.141", 
  "url": "http://httpbin.org/post"
}



In [6]:
import requests

res = requests.get('http://www.baidu.com')
print(res.headers)

{'Connection': 'close', 'Transfer-Encoding': 'chunked', 'Cache-Control': 'private, no-cache, no-store, proxy-revalidate, no-transform', 'Content-Encoding': 'gzip', 'Content-Type': 'text/html', 'Date': 'Sun, 16 Oct 2022 02:50:17 GMT', 'Last-Modified': 'Mon, 23 Jan 2017 13:27:36 GMT', 'Pragma': 'no-cache', 'Server': 'bfe/1.0.8.18', 'Set-Cookie': 'BDORZ=27315; max-age=86400; domain=.baidu.com; path=/'}


In [20]:
mDict = {'q16m7': 1, 'q06m3': 0, 'q10m4': 0, 'q12m6': 1, 'q00m0': 1, 'q04m1': 0, 'q05m2': 0, 'q11m5': 0, 'q16m24': 1, 'q06m14': 0, 'q15m23': 0, 'q01m9': 1, 'q03m11': 1, 'q12m20': 1, 'q13m21': 1, 'q05m13': 0, 'q08m16': 1, 'q10m18': 1, 'q11m19': 1, 'q00m8': 1, 'q04m12': 1, 'q09m17': 0, 'q14m22': 0, 'q02m10': 1, 'q07m15': 1}

In [23]:
import IandM
[mDict[j] for i in IandM.Q_ALL for j in mDict if j[1:3] == i[1:]]

[1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1]

In [ ]:
11111010000110

In [25]:
for _ in range(10):
    with open('test.txt','a') as f:
        f.write('1')

In [31]:
a = [1,3,4]
b=''.join([f'{i}' for i in a]+['\n'])
with open('test.txt','a') as f:
    f.write(b)

In [3]:
from sympy import *
t = symbols('t')
CZ1 = solve((1-exp(-t/21400))/4 + (1-exp(-t/21400))/2 - 0.00101201, t)
H1 = solve((1-exp(-t/21400))/4 + (1-exp(-t/21400))/2 - 0.000744128, t)
CZ2 = solve((1-exp(-t/27600))/4 + (1-exp(-t/27600))/2 - 0.00101201, t)
H2 = solve((1-exp(-t/27600))/4 + (1-exp(-t/27600))/2 - 0.000744128, t)
print(CZ1,H1,CZ2,H2)

[28.8955180893951] [21.2429923471094] [37.2671167881918] [27.3975041486083]


In [4]:
nsolve((1-exp(-t/21400))/4 + (1-exp(-t/27600))/2 - 0.00101201, t, 1)

33.9854254766436

In [5]:
nsolve((1-exp(-t/21400))/4 + (1-exp(-t/27600))/2 - 0.000744128, t, 1)

24.9848481286125

In [6]:
1/(1/2/21400+1/27600)

16779.545454545456

In [7]:
nsolve((1-exp(-t/21400))/4 + (1-exp(-t/16779.545454545456))/2 - 0.00101201, t, 1)

24.4139625294932

In [9]:
nsolve((1-exp(-t/21400))/4 + (1-exp(-t/16779.545454545456))/2 - 0.000744128, t, 1)

17.9482680362235

In [11]:
nsolve((1-exp(-t/18600))/4 + (1-exp(-t/29400))/2 - 0.000760504, t, 1)

24.9907567383947

In [13]:
nsolve((1-exp(-t/18600))/4 + (1-exp(-t/29400))/2 - 0.00103429, t, 20)

33.9941160226406

In [9]:
class CLanguage:
    def __init__(self,name) -> None:
        self.name = name
    def test(self):
        print(self.name)
CLanguage('c').test()


c
